### ISSUE TITLE
Shutdown Order 

### ISSUE THREAD

**Issue by mulloymorrow** [code-monastery/dropwizard-kinesis#5]
Bug with shutdown order. 

```bash
ERROR [2016-02-24 23:31:16,299] com.amazonaws.services.kinesis.clientlibrary.lib.worker.SimpleWorker: Worker.run caught exception, sleeping for 1000 milli seconds!
! java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6a0e2a4a rejected from java.util.concurrent.ThreadPoolExecutor@782b0699[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 48]
! at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[na:1.8.0_60]
! at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:1.8.0_60]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.checkAndSubmitNextTask(ShardConsumer.java:163) ~[amazon-kinesis-client-1.6.1.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardConsumer.consumeShard(ShardConsumer.java:125) ~[amazon-kinesis-client-1.6.1.jar:na]
! at com.amazonaws.services.kinesis.clientlibrary.lib.worker.SimpleWorker.run(SimpleWorker.java:111) ~[dropwizard-kinesis-0.9.2.5.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
```

**Comment by randyp** [comment]
We believe this to be taken care of since 0.9.6
